# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeepDetectChatBots' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DeepDetectChatBots
  pod 'JSQSystemSoundPlayer'
# pod 'JSQMessagesViewController', '~> 7.3.4'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ASIHTTPRequest'
pod 'Reachability', '~> 3.2'
pod 'NSData+Base64'
pod 'JSONModel'
pod 'NSString+Emoji'
pod 'SDWebImage', '~>3.8'
pod 'Cloudinary'
pod 'RestKit', '0.27.0'

  target 'DeepDetectChatBotsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeepDetectChatBotsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
