source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

# For latest release in cocoapods
pod 'JSQSystemSoundPlayer'
# pod 'JSQMessagesViewController', '~> 7.3.4'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'ASIHTTPRequest'
pod 'Reachability', '~> 3.2'
pod 'NSData+Base64'
pod 'JSONModel'
pod 'NSString+Emoji'
pod 'SDWebImage', '~>3.8'
pod 'Cloudinary'
pod 'RestKit', '~> 0.26', :inhibit_warnings => true

target 'DeepDetectChatBots' do
    
end
